FROM php:8.3.4-fpm

RUN apt-get update && apt-get install -y \
    libxml2-dev \
    libonig-dev \
    git \
    zip \
    unzip \
    vim \
    libpq-dev \
    && docker-php-ext-configure intl \
    && docker-php-ext-install pdo pdo_pgsql intl dom xml mbstring

RUN curl -sSk https://getcomposer.org/installer | php -- --disable-tls && \
    mv composer.phar /usr/local/bin/composer

WORKDIR /var/www/html